trigger:
  branches:
    exclude:
      - '*'

pr: none

jobs:
- job: AddTaskJob
  displayName: 'Add a Task'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: echo 'Running the original steps...'
    displayName: 'Original Step'
  - task: UseNode@1
    displayName: 'Add a Node.js task'
    inputs:
      versionSpec: '16'
  - script: echo 'Running the updated steps...'
    displayName: 'Updated Step'