jobs:
- job: BuildAndRelease
  displayName: 'Build and Release Task'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: echo 'Running the build step...'
    displayName: 'Build Step'
    # Add your build commands here

  - task: buildandreleasetask@1
    displayName: 'Custom Build and Release Task'
    inputs:
      samplestring: 'Test'
    # Add any additional inputs or configurations for the task here

  - script: echo 'Running the release step...'
    displayName: 'Release Step'